language: c
dist: bionic
matrix:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:dciabrin/ngdevkit'
            # bionic lacks python3-pygame, so install it from this ppa
            - sourceline: 'ppa:thopiekar/pygame'
          packages:
            - ngdevkit
            - ngdevkit-gngeo
            - zip
            - pkg-config
            - imagemagick
            - sox
            - libsox-fmt-mp3

    - name: "macOS"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          taps: dciabrin/ngdevkit
          packages:
            - ngdevkit
            - ngdevkit-gngeo
            - zip
            - pkg-config
            - imagemagick
            - sox
            - autoconf
            - automake
      env:
        PY3PATH="/usr/local/opt/python3/bin"
      before_script:
        - $PY3PATH/pip3 install pygame

script:
  - if [ -n "$PY3PATH" ]; then export PATH=$PY3PATH:$PATH; fi
  - git submodule update --init --recursive
  - autoreconf -iv
  - ./configure
  - make
