language: c
dist: bionic
matrix:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:dciabrin/ngdevkit'
            # bionic lacks python3-pygame, so install it from this ppa
            - sourceline: 'ppa:thopiekar/pygame'
          packages:
            - ngdevkit
            - ngdevkit-gngeo
            - zip
            - pkg-config
            - imagemagick

script:
  - git submodule update --init --recursive
  - autoreconf -iv
  - ./configure
  - make
